# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc9115b5628f8505f3aabe66e2a1fab27d2db3ad8495ba54b2674d21153432c88ba60effb0d6e41d50bd5a80ad6b04971ae9d938a728a7ddc0dcedf0199fad6a

test:
  secret_key_base: 7d75161079fe62effecc17f0df7140626b719c2d1221e915ab37dab5d437cb9ef097c4b2b43f67d7ee717b9d72a74502c43a2687d1c2f58b770b45adab41f2b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>